# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/ee.cooper.edu/user/a/alvee.ahmed/aahmed_oled/aahmed_oled.srcs/sources_1/bd/design_1/ip/design_1_ZedboardOLED_0_0/design_1_ZedboardOLED_0_0.xci
# IP: The module: 'design_1_ZedboardOLED_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /afs/ee.cooper.edu/user/a/alvee.ahmed/aahmed_oled/aahmed_oled.srcs/sources_1/bd/design_1/ip/design_1_ZedboardOLED_0_0/src/charLib/charLib.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet

# XDC: /afs/ee.cooper.edu/user/a/alvee.ahmed/aahmed_oled/aahmed_oled.srcs/sources_1/bd/design_1/ip/design_1_ZedboardOLED_0_0/src/charLib/charLib_ooc.xdc

# IP: /afs/ee.cooper.edu/user/a/alvee.ahmed/aahmed_oled/aahmed_oled.srcs/sources_1/bd/design_1/ip/design_1_ZedboardOLED_0_0/design_1_ZedboardOLED_0_0.xci
# IP: The module: 'design_1_ZedboardOLED_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /afs/ee.cooper.edu/user/a/alvee.ahmed/aahmed_oled/aahmed_oled.srcs/sources_1/bd/design_1/ip/design_1_ZedboardOLED_0_0/src/charLib/charLib.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet

# XDC: /afs/ee.cooper.edu/user/a/alvee.ahmed/aahmed_oled/aahmed_oled.srcs/sources_1/bd/design_1/ip/design_1_ZedboardOLED_0_0/src/charLib/charLib_ooc.xdc
