# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/oledControl.xdc

# Block Designs: bd/oledSystem/oledSystem.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oledSystem || ORIG_REF_NAME==oledSystem} -quiet] -quiet

# IP: bd/oledSystem/ip/oledSystem_processing_system7_0_0/oledSystem_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oledSystem_processing_system7_0_0 || ORIG_REF_NAME==oledSystem_processing_system7_0_0} -quiet] -quiet

# IP: bd/oledSystem/ip/oledSystem_oledControl_IP_0_0/oledSystem_oledControl_IP_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oledSystem_oledControl_IP_0_0 || ORIG_REF_NAME==oledSystem_oledControl_IP_0_0} -quiet] -quiet

# IP: bd/oledSystem/ip/oledSystem_ps7_0_axi_periph_0/oledSystem_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oledSystem_ps7_0_axi_periph_0 || ORIG_REF_NAME==oledSystem_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/oledSystem/ip/oledSystem_rst_ps7_0_100M_0/oledSystem_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oledSystem_rst_ps7_0_100M_0 || ORIG_REF_NAME==oledSystem_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/oledSystem/ip/oledSystem_auto_pc_0/oledSystem_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oledSystem_auto_pc_0 || ORIG_REF_NAME==oledSystem_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/jaeho/junior_fall/hardware/proj2/oledController/oledController.gen/sources_1/bd/oledSystem/oledSystem_ooc.xdc
