# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jaeho/junior_fall/hardware/proj2/oledController/oledController.srcs/sources_1/bd/oledSystem/ip/oledSystem_processing_system7_0_0/oledSystem_processing_system7_0_0.xci
# IP: The module: 'oledSystem_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jaeho/junior_fall/hardware/proj2/oledController/oledController.gen/sources_1/bd/oledSystem/ip/oledSystem_processing_system7_0_0/oledSystem_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'oledSystem_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/jaeho/junior_fall/hardware/proj2/oledController/oledController.srcs/sources_1/bd/oledSystem/ip/oledSystem_processing_system7_0_0/oledSystem_processing_system7_0_0.xci
# IP: The module: 'oledSystem_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jaeho/junior_fall/hardware/proj2/oledController/oledController.gen/sources_1/bd/oledSystem/ip/oledSystem_processing_system7_0_0/oledSystem_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'oledSystem_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
