function Hd = cascade
%CASCADE Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.1 and DSP System Toolbox 24.1.
% Generated on: 30-Oct-2024 23:26:08

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 44;  % Sampling Frequency

Fpass = 2.5;         % Passband Frequency
Fstop = 4;           % Stopband Frequency
Apass = 3;           % Passband Ripple (dB)
Astop = 95;          % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

reorder(Hd, 'up');



reorder(Hd, 'auto');



% [EOF]
