domain_path: C:\Users\jaeho\junior_fall\hardware\proj2\oledController\zedboard_platform\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
